import os
import io
import requests
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_ORIENT
from docx.enum.table import WD_ROW_HEIGHT_RULE

def create_complex_docx(filename="complex_test.docx"):
    print("Initializing layout stress test document...")
    doc = Document()

    # --- 1. HEADERS & FOOTERS ---
    section = doc.sections[0]
    header = section.header
    header_para = header.paragraphs[0]
    header_para.text = "STRESS TEST EXTREME - DO NOT DISTRIBUTE\t\tCONFIDENTIAL"
    header_para.style.font.color.rgb = RGBColor(128, 128, 128)
    
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = "Generated by automated CI/CD pipeline. Page 1 of ?"
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # --- 2. COMPLEX TYPOGRAPHY ---
    doc.add_heading('The Ultimate Layout Stress Test', 0)
    
    p = doc.add_paragraph('This paragraph tests ')
    p.add_run('bold text, ').bold = True
    p.add_run('italic text, ').italic = True
    p.add_run('underlined text, ').underline = True
    p.add_run('strikethrough, ').font.strike = True
    
    sub = p.add_run('subscript')
    sub.font.subscript = True
    p.add_run(', and ')
    
    sup = p.add_run('superscript')
    sup.font.superscript = True
    p.add_run('. We can also change ')
    
    color_run = p.add_run('font colors')
    color_run.font.color.rgb = RGBColor(255, 0, 0)
    p.add_run(' and ')
    
    size_run = p.add_run('font sizes wildly.')
    size_run.font.size = Pt(24)

    doc.add_paragraph("Right-aligned paragraph testing margins and alignment.", 
                      style='Normal').alignment = WD_ALIGN_PARAGRAPH.RIGHT

    # --- 3. NESTED LISTS ---
    doc.add_heading('Lists and Indentation', level=1)
    doc.add_paragraph('Level 1 Bullet', style='List Bullet')
    doc.add_paragraph('Level 2 Bullet (Indented)', style='List Bullet 2')
    doc.add_paragraph('Level 3 Bullet (Deeply Indented)', style='List Bullet 3')
    doc.add_paragraph('Level 1 Numbered', style='List Number')
    doc.add_paragraph('Level 2 Numbered', style='List Number 2')

    # --- 4. COMPLEX TABLES WITH MERGED CELLS ---
    doc.add_heading('Complex Table Layouts', level=1)
    table = doc.add_table(rows=4, cols=4)
    table.style = 'Light Shading Accent 1' # Built-in Word style
    
    # Merge cells in the first row to create a master header
    a = table.cell(0, 0)
    b = table.cell(0, 3)
    a.merge(b)
    table.cell(0, 0).text = 'MASTER MERGED HEADER ROW'
    table.cell(0, 0).paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Fill data using explicit paragraphs instead of \n to avoid LibreOffice fragmentation
    for row in range(1, 4):
        for col in range(4):
            cell = table.cell(row, col)
            cell.text = f"R{row}C{col}"
            cell.add_paragraph("Multi-line") # Safely adds the second line

    # --- 5. EMBEDDED IMAGES & SIZING ---
    doc.add_heading('Image Rendering', level=1)
    try:
        url = "https://picsum.photos/600/200" # Random placeholder image
        response = requests.get(url)
        image_stream = io.BytesIO(response.content)
        # Shrunk image width slightly from 5.5 to 4.0 to prevent LibreOffice page-wrap panic
        doc.add_picture(image_stream, width=Inches(4.0)) 
        img_p = doc.paragraphs[-1]
        img_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph("Figure 1: Center-aligned dynamically fetched image.", style='Caption')
    except Exception as e:
        doc.add_paragraph(f"[Failed to fetch image: {e}]")

    # --- 6. SECTION BREAKS & ORIENTATION CHANGES ---
    # This is the ultimate test: changing from Portrait to Landscape halfway through
    doc.add_page_break()
    new_section = doc.add_section()
    new_section.orientation = WD_ORIENT.LANDSCAPE
    
    # Adjust width and height to match landscape
    new_width, new_height = new_section.page_height, new_section.page_width
    new_section.page_width = new_width
    new_section.page_height = new_height

    doc.add_heading('Landscape Mode Rendering', level=1)
    doc.add_paragraph('This entire page should be oriented sideways. If the PDF generator fails to read section breaks, this will render in standard portrait mode and the text will be squished.')

    # Save the monster document
    doc.save(filename)
    print(f"Success! {filename} generated successfully.")

if __name__ == "__main__":
    create_complex_docx()